// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBINGWP5Z9CNavPifrm_tPEOJb1x-GYixY',
    appId: '1:437151299766:web:c4db2b24c2faaff57bce17',
    messagingSenderId: '437151299766',
    projectId: 'simple-crud-ac513',
    authDomain: 'simple-crud-ac513.firebaseapp.com',
    storageBucket: 'simple-crud-ac513.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCha3Q2yoUNnmIDmFTXNiVWAkR5fD-WOj8',
    appId: '1:437151299766:android:146d5204ba58970a7bce17',
    messagingSenderId: '437151299766',
    projectId: 'simple-crud-ac513',
    storageBucket: 'simple-crud-ac513.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQp_6i_9wZlZjwK3vCPSP0P9ZMJH8lj2c',
    appId: '1:437151299766:ios:a83e9154088941047bce17',
    messagingSenderId: '437151299766',
    projectId: 'simple-crud-ac513',
    storageBucket: 'simple-crud-ac513.appspot.com',
    iosBundleId: 'com.example.simplecrudwithfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQp_6i_9wZlZjwK3vCPSP0P9ZMJH8lj2c',
    appId: '1:437151299766:ios:a83e9154088941047bce17',
    messagingSenderId: '437151299766',
    projectId: 'simple-crud-ac513',
    storageBucket: 'simple-crud-ac513.appspot.com',
    iosBundleId: 'com.example.simplecrudwithfirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBINGWP5Z9CNavPifrm_tPEOJb1x-GYixY',
    appId: '1:437151299766:web:0472debb6bb2f97c7bce17',
    messagingSenderId: '437151299766',
    projectId: 'simple-crud-ac513',
    authDomain: 'simple-crud-ac513.firebaseapp.com',
    storageBucket: 'simple-crud-ac513.appspot.com',
  );
}
